# Numpy Random Module
   - rand : Random values in a given shape
   - randm : return a sample or samples from "standard normal" distribution
   - randint : return random integers from low(incusive) to high(exclusive) 
   - radom : return random floats in the half open interval (0.0,1.0]
   - choice : generates a random sample from a 1-D array
   - shuffle : shuffle the contents of the sequence

In [1]:
import numpy as np

In [9]:
a=np.arange(10)
print(a)
a=a+5
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [12]:
# shuffle
np.random.shuffle(a)
print(a)

[13  7  5 14 10  8 11  6  9 12]


In [15]:
# generate array of random number : rand

a=np.random.rand(2,3)
print(a)

[[0.32622789 0.67545943 0.03373904]
 [0.80045505 0.25594066 0.57132883]]


In [17]:
# generate array from SND :randn
a=np.random.randn(2,3)
print(a)

[[ 0.8088044   1.3937816   0.97757439]
 [ 1.6683116  -0.2207472  -1.28728399]]


In [18]:
np.random.randint(5,10,3)

array([6, 5, 6])

In [21]:
ele=np.random.choice([1,2,3,4,5,6,7])
print(ele)

7


In [27]:
a=[1,4,3,6,9,5,2]
li=np.random.shuffle(a)
print(li)

None
