# some statistical function - Statistics
- min,max
- mean
- median
- average
- variance
- standard deviationM

In [2]:
import numpy as np

In [6]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)

# min - max row wise
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [9]:
# mean -average
b=np.array([1,2,3,4,5])
print(sum(b)/5)
print(np.mean(b))

print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))


3.0
3.0
3.125
[4.  4.  2.5 2. ]
[2.5  3.75]


In [14]:
# median
c=np.array([1,5,4,2,0])
print(np.median(c))

# mean vs average is weighted
w=np.array([1,2,3,4,5])
print(np.mean(w))
print(np.average(w,weights=w))




2.0
3.0
3.6666666666666665


In [18]:
# standard deviation in python
u=np.mean(c)
mystd=np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

print(np.std(c))


# variance -square of standard deviation
print(mystd**2)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
