In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
dfx=pd.read_csv(".\Training Data\Diabetes_XTrain.csv")
dfy=pd.read_csv(".\Training Data\Diabetes_YTrain.csv")

In [3]:
xdata=dfx.values
ydata=dfy.values

In [4]:
#x_train,x_test,y_train,y_test=train_test_split(xdata,ydata,random_state=5,test_size=0.2)

In [160]:
knn=KNeighborsClassifier(n_neighbors=17)


In [161]:
knn.fit(xdata,ydata)

C:\Users\Dell\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=17, p=2,
           weights='uniform')

In [162]:
#y_pred=knn.predict(x_test)

In [163]:
#acc=metrics.accuracy_score(y_pred,y_test)

In [164]:
#print(acc)

In [165]:
#print(y_pred)

In [166]:
#print(y_test.reshape(-1))

In [167]:
dfxtest=pd.read_csv("Diabetes_Xtest.csv")

In [168]:
testData=dfxtest.values

In [169]:
print(testData)

[[0.00e+00 1.80e+02 9.00e+01 ... 3.65e+01 3.14e-01 3.50e+01]
 [2.00e+00 9.30e+01 6.40e+01 ... 3.80e+01 6.74e-01 2.30e+01]
 [2.00e+00 1.14e+02 6.80e+01 ... 2.87e+01 9.20e-02 2.50e+01]
 ...
 [0.00e+00 1.62e+02 7.60e+01 ... 4.96e+01 3.64e-01 2.60e+01]
 [1.20e+01 8.40e+01 7.20e+01 ... 2.97e+01 2.97e-01 4.60e+01]
 [0.00e+00 9.40e+01 0.00e+00 ... 0.00e+00 2.56e-01 2.50e+01]]


In [170]:
predict=knn.predict(testData)

In [171]:
print(type(predict[0]))

<class 'numpy.int64'>


In [172]:
p=pd.DataFrame(predict,columns=["Outcome"])

In [173]:
p.to_csv("submission.csv",index=False)

In [174]:
subdata=pd.read_csv("sample_submission.csv")

In [175]:
subdata.dtypes

Outcome    int64
dtype: object

In [176]:
file=pd.read_csv("submission.csv")
file.dtypes

Outcome    int64
dtype: object