In [97]:
import numpy as np

In [98]:
x=[]
for i in range(100):
    x.append(i)

In [99]:
#print(x)
print(x[:5])
print(x[6:])


[0, 1, 2, 3, 4]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [100]:
x=np.array(x)
x.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [101]:
x=x.reshape(20,5)

In [102]:
x[:5,1]

array([ 1,  6, 11, 16, 21])

In [103]:
x[:5,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
x.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [105]:
import pandas as pd

In [106]:
dfx=pd.read_csv("xdata.csv")

In [107]:
X=dfx.values

In [108]:
print(X)

[[ 1.00000000e+00  3.51627900e+00  3.71975047e+00]
 [ 2.00000000e+00  4.60649561e+00  3.41437943e+00]
 [ 3.00000000e+00  4.67701056e+00  3.04724443e+00]
 ...
 [ 3.97000000e+02  7.89625683e-01  9.31669806e-01]
 [ 3.98000000e+02 -1.00253042e+00 -6.76162472e-01]
 [ 3.99000000e+02  2.92386778e-01  5.61177823e-01]]


In [109]:
print(X.shape)
X=X[:,1:]
print(X.shape)
print(X)

(399, 3)
(399, 2)
[[ 3.516279    3.71975047]
 [ 4.60649561  3.41437943]
 [ 4.67701056  3.04724443]
 [ 4.15772454  3.13867678]
 [ 3.15443087  3.61985805]
 [ 3.41751854  4.59164128]
 [ 1.61124605  3.39835595]
 [ 4.28808719  4.04396943]
 [ 3.19607968  4.95114323]
 [ 1.6258394   4.90239967]
 [ 2.82894521  3.91445026]
 [ 2.28966729  5.06896877]
 [ 2.89206152  3.66529487]
 [ 2.33634919  4.77256166]
 [ 3.67027475  3.79730296]
 [ 2.30717865  4.73262822]
 [ 3.15130599  3.43648588]
 [ 4.14502484  2.94851846]
 [ 2.17253471  3.6488889 ]
 [ 3.39390371  4.13447274]
 [ 1.59644351  4.43875703]
 [ 3.38348549  4.02119623]
 [ 5.08330979  4.03477733]
 [ 1.21644435  4.31174386]
 [ 4.15939179  2.54939222]
 [ 2.2392529   4.33673035]
 [ 2.99918423  5.63946256]
 [ 3.10384641  3.0156258 ]
 [ 2.47612428  4.12508079]
 [ 3.2447355   2.49239435]
 [ 2.03739207  5.03815425]
 [ 0.60211258  5.29511732]
 [ 4.96947578  3.37368252]
 [ 3.21264629  3.83263367]
 [ 4.37032895  4.13833792]
 [ 3.69323485  3.24528272]
 [ 3.09839

In [110]:
dfy=pd.read_csv("ydata.csv")
Y=dfy.values

In [111]:
print(Y.shape)

(399, 2)


In [112]:
Y=Y[:,1:]
print(Y)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [113]:
Y=Y.reshape(-1)

In [114]:
print(Y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [115]:
print(X[4])

[3.15443087 3.61985805]


In [116]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

print(type(X))
qpoin=[2,3]
m=X.shape[0];
vals=[]
for i in range(m):
    x=dist(qpoin,X[i])
    vals.append((x,Y[i]))

<class 'numpy.ndarray'>


In [117]:

print(vals)

[(1.678434612099308, 0.0), (2.6392289924931336, 0.0), (2.677427415476787, 0.0), (2.162176316467576, 0.0), (1.3103185241666486, 0.0), (2.1313565594951718, 0.0), (0.5566121542162752, 0.0), (2.5149980425084397, 0.0), (2.2885730266215156, 0.0), (1.9388451872263994, 0.0), (1.234248532389249, 0.0), (2.0891478909380723, 0.0), (1.1128301893675936, 0.0), (1.8041911219583946, 0.0), (1.850813270805008, 0.0), (1.759647489897214, 0.0), (1.2312698348170081, 0.0), (2.14564254326479, 0.0), (0.6714350539723669, 0.0), (1.7972189516232564, 0.0), (1.4942823189174368, 0.0), (1.7195562920465988, 0.0), (3.252316618164895, 0.0), (1.5279500710850396, 0.0), (2.20590577223664, 0.0), (1.357972747075832, 0.0), (2.8222564973082562, 0.0), (1.1039570053458476, 0.0), (1.2216796305359838, 0.0), (1.3442581416980646, 0.0), (2.0384972209984134, 0.0), (2.687313297787955, 0.0), (2.992895763088676, 0.0), (1.47098262001708, 0.0), (2.6295004361067598, 0.0), (1.7109084883591896, 0.0), (1.1533917405973981, 0.0), (1.3645836636893

In [118]:
vals=sorted(vals)
print(vals)

[(0.11937694641032923, 0.0), (0.2439279914285809, 1.0), (0.24435617231406334, 0.0), (0.32750157532483204, 0.0), (0.44941873737939525, 1.0), (0.5107561566676762, 0.0), (0.5566121542162752, 0.0), (0.6060803906018917, 0.0), (0.627899040480778, 0.0), (0.6564414681843971, 0.0), (0.6714350539723669, 0.0), (0.7341843351195955, 1.0), (0.7490959838586542, 0.0), (0.7576002522014041, 0.0), (0.7685641350714514, 0.0), (0.7954986088357634, 0.0), (0.804577267397058, 1.0), (0.8049463584938802, 0.0), (0.8300319838679158, 0.0), (0.8600892474332242, 0.0), (0.8673610010001733, 0.0), (0.8745431500156774, 1.0), (0.8900938608220971, 0.0), (0.8909905616851129, 0.0), (0.9123860110995071, 0.0), (0.9186852861561159, 1.0), (0.9341696534929479, 0.0), (0.9852534989701442, 0.0), (0.9947363003347277, 0.0), (1.0008894882006691, 1.0), (1.013202323019086, 0.0), (1.0247693141101797, 0.0), (1.037389201737403, 0.0), (1.0382311868934855, 0.0), (1.0397473799538726, 1.0), (1.0593106277218014, 0.0), (1.059503535828205, 0.0), (

In [119]:
vals=vals[:20]
print(vals)

[(0.11937694641032923, 0.0), (0.2439279914285809, 1.0), (0.24435617231406334, 0.0), (0.32750157532483204, 0.0), (0.44941873737939525, 1.0), (0.5107561566676762, 0.0), (0.5566121542162752, 0.0), (0.6060803906018917, 0.0), (0.627899040480778, 0.0), (0.6564414681843971, 0.0), (0.6714350539723669, 0.0), (0.7341843351195955, 1.0), (0.7490959838586542, 0.0), (0.7576002522014041, 0.0), (0.7685641350714514, 0.0), (0.7954986088357634, 0.0), (0.804577267397058, 1.0), (0.8049463584938802, 0.0), (0.8300319838679158, 0.0), (0.8600892474332242, 0.0)]


In [120]:
vals=np.array(vals)
print(vals)
print(vals[:,1])

[[0.11937695 0.        ]
 [0.24392799 1.        ]
 [0.24435617 0.        ]
 [0.32750158 0.        ]
 [0.44941874 1.        ]
 [0.51075616 0.        ]
 [0.55661215 0.        ]
 [0.60608039 0.        ]
 [0.62789904 0.        ]
 [0.65644147 0.        ]
 [0.67143505 0.        ]
 [0.73418434 1.        ]
 [0.74909598 0.        ]
 [0.75760025 0.        ]
 [0.76856414 0.        ]
 [0.79549861 0.        ]
 [0.80457727 1.        ]
 [0.80494636 0.        ]
 [0.83003198 0.        ]
 [0.86008925 0.        ]]
[0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]


In [121]:
new_vals=np.unique(vals[:,1],return_counts=True)

In [122]:
print(new_vals)

(array([0., 1.]), array([16,  4], dtype=int64))


In [126]:
index=new_vals[1].argmax()

In [128]:
pred=new_vals[0][index]
print(pred)

0.0
