In [3]:
n=10

In [4]:
print(n)

10


In [5]:
n=int(input())

5


In [6]:
print(type(n))

<class 'int'>


In [7]:
n=int(input())
if n%2==0:
    print("Even")
else:
    print("odd")

45
odd


In [9]:
for i in range(10):
    print(i)

while i<10:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9
9


In [11]:
li=[]
for i in range(0,10,2):
    li.append(i)
    
print(li)

[0, 2, 4, 6, 8]


In [13]:
print(li[1])

2


In [14]:
li[1]=34

In [15]:
print(li)

[0, 34, 4, 6, 8]


In [16]:
li[1]=li[1]+20

In [17]:
print(li)

[0, 54, 4, 6, 8]


In [18]:
import numpy as np

In [21]:
arr=np.array(li)

In [22]:
print(arr)

[ 0 54  4  6  8]


In [23]:
print(arr+2)

[ 2 56  6  8 10]


In [24]:
print(arr*5)

[  0 270  20  30  40]


In [25]:
np.mean(arr)

14.4

In [30]:
a=np.array([[1,2,3,4,5,6],[6,5,4,3,2,1]])
print(a)
np.shape(a)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]


(2, 6)

In [31]:
print(a[0][5])

6


In [33]:
print(a[1,:])

[6 5 4 3 2 1]


In [ ]:
import n