In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# import datasets
data=pd.read_csv('./datasets/mushrooms.csv')
print(data.shape)

(8124, 23)


In [3]:
### the data is alphabetical we need to convert it to numerical data ###

# encoding of data

In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [5]:
le=LabelEncoder()
ds=data.apply(le.fit_transform)
ds=ds.values

In [6]:
print(ds)
X=ds[:,1:]
Y=ds[:,0]

[[1 5 2 ... 2 3 5]
 [0 5 2 ... 3 2 1]
 [0 0 2 ... 3 2 3]
 ...
 [0 2 2 ... 0 1 2]
 [1 3 3 ... 7 4 2]
 [0 5 2 ... 4 1 2]]


In [7]:
print(Y)

[1 0 0 ... 0 1 0]


In [8]:
print(X[:5,:])

[[5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


In [9]:
# break data into test and train

In [10]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

In [11]:
print(xtrain.shape,ytrain.shape)
print(xtest.shape,ytest.shape)

(6499, 22) (6499,)
(1625, 22) (1625,)


# BUILDING OUR CLASSIFIER

In [12]:
a=np.array([1,1,0,0,1,0,1,0,1,0])
np.sum(a==1)

5

In [13]:
def prior_prob(y_train,label):
    total_examples=y_train.shape[0]
    class_examples=np.sum(y_train==label)
    return class_examples/float(total_examples)

In [14]:
prior_prob(a,1)

0.5

In [15]:
def conditional_probability(x_train,y_train,feature_col,feature_val,label):
    x_filtered=x_train[y_train==label]
    numerator=np.sum(x_filtered[:,feature_col]==feature_val)
    denominator=np.sum(y_train==label)
    
    return numerator/float(denominator)

In [16]:
def predict(x_train,y_train,xtest):
    ### xtest is a single example ###
    classes=np.unique(y_train)
    n_feature=x_train.shape[1]
    post_prob=[]
    for label in classes:
        likelihood=1.0
        for f in range(n_feature):
            cond=conditional_probability(x_train,y_train,f,xtest[f],label)
            likelihood*=cond
        prior=prior_prob(y_train,label)
        post=likelihood*prior
        post_prob.append(post)
        
    return np.argmax(post_prob)

In [17]:
output=predict(xtrain,ytrain,xtest[4])
print(output)

1


In [18]:
ypred=[]
for i in range(xtest.shape[0]):
    y=predict(xtrain,ytrain,xtest[i])
    ypred.append(y)
    
yped=np.array(ypred)

In [19]:
print(yped)

[0 1 1 ... 0 0 1]


In [20]:
print(ytest)

[0 1 1 ... 0 0 1]


In [21]:
from sklearn.metrics import accuracy_score


In [22]:
acc=accuracy_score(ytest,ypred)

In [23]:
print(acc)

0.9987692307692307


# Confusion matrix

In [24]:
from sklearn.metrics import confusion_matrix

In [27]:
cm=confusion_matrix()

ValueError: Found input variables with inconsistent numbers of samples: [8124, 1625]